#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           6
bspc config top_padding          24
bspc config bottom_padding       2
bspc config left_padding         2
bspc config right_padding        2
bspc config focused_border_color \#007ACC
bspc config urgent_border_color  \#A54242

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gnome-system-monitor state=floating follow=on
bspc rule -a Gnome-control-center state=floating follow=on center=true
bspc rule -a Eog state=floating follow=on center=true
bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a Grub-customizer state=floating follow=on center=true
bspc rule -a GParted state=floating follow=on center=true
bspc rule -a Org.gnome.DejaDup state=floating follow=on center=true
bspc rule -a Gnome-tweaks state=floating follow=on center=true
bspc rule -a Gtk3-icon-browser state=floating follow=on center=true
bspc rule -a Pavucontrol state=floating follow=on center=true
bspc rule -a Gnome-power-statistics state=floating follow=on center=true
bspc rule -a Yad state=floating follow=on
bspc rule -a Software-properties-gtk state=floating follow=on center=true
bspc rule -a Gufw.py state=floating follow=on center=true
bspc rule -a Totem state=floating follow=on center=true rectangle=1600x900+0+0
bspc rule -a Shotwell state=floating follow=on center=true rectangle=1600x900+0+0

# Auto start apps
xsetroot -cursor_name left_ptr &

# Compositor
picom -b &

# Policy Kit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# Default to Gnome Theme Settings
/usr/libexec/gsd-xsettings &

# Wallpaper
# feh --bg-fill /home/mukul/Pictures/Wallpapers/Dark_Mode_green_blue.jpg &
nitrogen --restore &

# Polybar
$HOME/.config/polybar/launch.sh &
# Desktop Widgets
$HOME/.config/conky/launch.sh &

# Default External Speaker and Mic
pactl set-default-sink alsa_output.usb-Logitech_G560_Gaming_Speaker_00000000-00.analog-stereo &
pactl set-default-source alsa_input.usb-046d_C270_HD_WEBCAM_C5566C60-02.mono-fallback &

# Network Manager UI
nm-applet &

# Set Num Lock on
numlockx on &

# Set Power Saving Off
xset s off &
xset -dpms &

# Check updates
check-updates.py &

# Clipboard Manager
parcellite -d &
